// Auto-generated by c_gen.py

#ifndef DATA_H_
#define DATA_H_

#include <stdint.h>

// 1D convolution data
// Input data
// A: input matrix [input_len x input_ch]
// F: filter matrix [kernel_len x input_ch x k_num]
// Output data
// R: output matrix [input_len x k_num]
// Stride: 1
// Padding: 0

// Macros
// ------
#define INPUT_LEN 8
#define INPUT_CH 4
#define KERNEL_LEN 3
#define K_NUM 2
#define STRIDE 1
#define PAD 0

// Input matrix size
#define A_SIZE 32
#define A_ROWS 4
#define A_COLS 8
#define F_SIZE 24
#define F_ROWS 2
#define F_COLS 4

// Output matrix size
#define R_SIZE 48
#define R_ROWS 2
#define R_COLS 6

// Input matrices
// --------------
extern int8_t A[];
extern int8_t F[];

// Output matrices
// ---------------
extern int32_t R[];

#endif // DATA_H_
